pipreqs/pipreqs.py
tests/_data/test.py
tests/test_pipreqs.py

1. local imports
```
λ ~/temp/ ls
main.py  models.py  models.pyc
```
Current directory's files are like these, and I imported `models` in `main.py`.
Cause a package named `models` exists in pypi, it is added to requirements file.
2. imported with "as"
```python
...
import ujson as json
...
```
In this case, it's package name is recognized invalid by `ujson as json`.

Fixed problems with local imports and imports with 'as'

---

pipreqs/pipreqs.py

str.partition() has nice advantages over str.split():
```python
to_append = item if "." not in item else item.split(".")[0]
to_append = item.partition(".")[0]
```
Also tightened up generate_requirements_file() to send all data in a single write() operation

str.partition() simplifies the logic, tighten up write()

---

pipreqs/pipreqs.py

`package_import` is a list, and on Python 3.4 it must be implicitly converted to a string before concatenation.

Fix for TypeError for implicit conversion

---

pipreqs/pipreqs.py
tests/test_pipreqs.py

* Fix for #13.
* Added tests for the new method `get_import_name_without_alias`

Handling multiple imports in the same line when using aliases

---

.gitignore
pipreqs/pipreqs.py

- Skip .git, env, \__pycache\__ when running get_all_imports()  
- In the previous version, pipreqs walks through `env` and generate unnecessary imports
- Change logging level to warning when encountering `Requirements.txt already exists`

Skip irreverent directory and change logging level

---

pipreqs/pipreqs.py
tests/_data/test.py
tests/_invalid_data/invalid.py
tests/test_pipreqs.py

Rationale: Using regex means that you can only find the imports that are at the top of the page without any spaces between them. There's likely other issues, but that was the one that bit me. 
Caveat: Old method would parse files with broken syntax. This one will not.

Walk Abstract Syntax Tree to find imports

---

pipreqs/pipreqs.py
tests/_data_duplicated_deps/db.py
tests/test_pipreqs.py

Test file:
```python
import pymongo
from bson.objectid import ObjectId
```
For this file `pipreqs` generates the following `requirements.txt`:
```
pymongo==3.2.1
pymongo==3.2.1
```
This pull-request fixes this unfortunate behaviour by patching `get_pkg_names` function.

Make pipreqs not write diplicate lines to requirements.txt file

---

.travis.yml
CONTRIBUTING.rst
setup.py
tox.ini

All tests pass on Python 3.5, so declare official support for it.

Explicitly support Python 3.5

---

pipreqs/pipreqs.py

Fix for #74. Previous PR was accidentally closed by me.

Exclude concurrent{,.futures} from stdlib if py2

---

.travis.yml
CONTRIBUTING.rst
setup.py
tox.ini

All tests pass under Python 3.6, so declare official support for it.
Closes #68.

Declare support for Python 3.6

---

pipreqs/mapping

https://pypi.org/project/arrow/ is https://github.com/crsmithdev/arrow/, the real arrow.
https://pypi.org/project/arrow-fatisar/ is https://github.com/fatisar/arrow, a completely random, outdated fork.

fix(pipreqs/mapping): correct arrow mapping

---

pipreqs/pipreqs.py

This change makes the `<path>` argument optional, defaulting to the
current working directory if omitted.
---
Ideally, this would have been accomplished via docopt, but optional
positional arguments with defaults are not supported at the moment [1, 2].
[1] https://github.com/docopt/docopt/issues/214
[2] https://github.com/docopt/docopt/issues/329

Support optional <path> argument

---

.travis.yml
tox.ini

By using tox instead of the default Travis-CI Python environments, we
ensure that we have a single entrypoint to testing both locally and in
CI. This reduces redundant code and makes it clear when test
environments don't match up on different platforms.

Run Travis-CI tests inside of tox

---

pipreqs/pipreqs.py

- Hoist non-file-reading logic outside of the file context manager
- Use a dict instead of a list for faster / more Pythonic lookups
- Use a set to simplify the add / append logic
- Move import sorting from `get_all_imports` to `get_pkg_names` for
to account for set ordering. This change may also affect #89.
- Add a docstring

Simplify get_pkg_names function

---

pipreqs/pipreqs.py

This change removes some redundancy in writing requirements and ensures that all changes to file output are reflected in stdout output and vice versa.

Consolidate logic for writing to a file and to stdout

---

pipreqs/mapping

Ref: https://github.com/bndr/pipreqs/issues/66#issuecomment-415642021  This is a wholly separate package from pycryptodome (which replaced pycrypto in #124 ). This uses the name `Cryptodome` in import statements, which differentiates it from pycrpytodome. This package works while pycryptodome causes problems, when building binaries of python programs in pyinstaller, thanks to having a completely different name. (See [replace Pycrypto in pyinstaller](https://github.com/pyinstaller/pyinstaller/issues/2365#issuecomment-384069038) )

Add Cryptodome:pycryptodomex

---

pipreqs/stdlib

Not technically in the stdlib but it doesn't really make sense for pipreqs to report setuptools as a dependency just because it's imported in `setup.py`.

Add setuptools to stdlib

---

pipreqs/mapping

For this package: https://pypi.org/project/patricia-trie/. Old, but I think it's the
only pure-python trie implementation on pypi.

Add patricia-trie mapping

---

pipreqs/pipreqs.py

when open fails, instead of raising the original error, the "f.close()" was erroring in the final clause.

bugfix: f.close() only required if open succeeded

---

pipreqs/mapping

Maps `functional` to `pyfunctional`. Fixes #232.

Add PyFunctional mapping

---

.travis.yml
tox.ini

Closes #235
I believe the pypy build, for some reason, was using older versions of our dependencies during its build process which caused it to fail. By upgrading pypy to pypy3, travis started using python 3 instead of 2.7 and pip 20 instead of 19 (like all other successfull builds). Somehow this fixed our issues, but it is important to note that neither the python nor the pip versions where responsible for the issue as noted in #235. 
I still don't know what exactly caused this, maybe upgrading the version of wheels in requirements.txt could also solve the problem, but at this point this is all speculation.

Fix Pypy Build

---

pipreqs/mapping

@alan-barzilay  Added `github3:github3.py` to mapping file
Fixes #226

Mapping for github3

---

pipreqs/mapping

Maps `hydra` to `hydra-core`. Fixes #244.

Add hydra-core mapping

---

pipreqs/pipreqs.py

When trying to generate requirements.txt and file is already existent, the user message produced asks for "Requirements.txt" instead of "requirements.txt". 
This may cause some trouble when used in case sensitive env, as well as in automated scripts.

Decaptalized file name in log msg

---

pipreqs/stdlib

Part of the standard lib since 3.7: https://docs.python.org/3.7/library/dataclasses.html

Update stdlib with dataclasses

---

.github/workflows/tests.yml
CONTRIBUTING.rst
setup.py
tox.ini

Require Python 3.7 by setting `python_requires` in setup.py. Also updates the CI, tests and docs.

Require Python 3.7 or higher

---

pipreqs/pipreqs.py

simply moved the check in init for requirements.txt ahead of searching for packages. Closes #285. Passes tox (3.7, 3.8, 3.9, pypy3, flake8)

resolve issue #285

---

pipreqs/mapping

Originally mapped to gevent-socketio, which is outdated and hasn't been updated since 2016. Anyone importing socketio is much more likely to mean python-socketio now.

Update mapping socketio to python-socketio

---

pipreqs/mapping

telegram is a hollow pypi package, so pipreqs will try to install that instead of python-telegram-bot, which have a module named telegram.

Mapping Telegram to python-telegram-bot

---

pipreqs/pipreqs.py
tests/test_pipreqs.py

When the function "parse_requirements.txt" does not find the file passed as a parameter, it just raises an OSError.
This PR changes that behavior. Now, when that happens, this function handles it by printing a helpful message to the user and ends the program execution immediately.

handle FileNotFoundError in parse_requirements function

---

tox.ini

The way we configured the `tox.ini` file makes flake8 not to be run. Tox only run python tests for the `flake8` environment.
With this PR, tox will run flake8 for the `pipreqs` and `tests` folders as desired.

Fix flake8 environment in tox.ini file

---

pipreqs/pipreqs.py
tests/_data_pyw/py.py
tests/_data_pyw/pyw.pyw
tests/test_pipreqs.py

Now, pipreqs will also scan imports in .pyw files by default.

add support for .pyw files

---

pipreqs/mapping

`jose` is a Python 2 package. `python-jose` is its Python 3 successor.

Add mapping `jose` -> `python-jose`

---

pipreqs/pipreqs.py

If there is no specific reason to call it `non-pin` in the explanation text and `no-pin` for the option, I would change the explanation text:
```
--mode <scheme>       Enables dynamic versioning with <compat>, <gt> or <non-pin> schemes
<compat> | e.g. Flask~=1.1.2
<gt>     | e.g. Flask>=1.1.2
<no-pin> | e.g. Flask
```

Doc: no-pin instead of non-pin for scheme

---

README.rst
pipreqs/pipreqs.py
tests/test_pipreqs.py

This PR introduces the `--ignore-errors` flag to pipreqs, allowing users to continue generating requirements.txt even if some files contain syntax errors. When this option is enabled, files with syntax errors will be skipped, and a warning will be logged instead of failing the entire process.
I initially worked on this without being aware of PR #287, which proposed a similar change. After finishing my implementation, I became aware of #287 and reviewed it carefully. While I appreciate the original contribution, I believe this PR still provides additional value for the following reasons:
**Includes a Test Case**
This PR adds a test (`test_ignore_errors`) to ensure the new flag works correctly. The previous PR did not include a test, which could make it harder to verify correctness and …

Add `--ignore-errors` to skip files with errors
