bndr/pipreqs

README.rst, pipreqs/pipreqs.py
Fix a typo, use str.format() in a few places, sort requirements list and update help text.
=> Output tuning

pipreqs/pipreqs.py
=> Exclude relative imports and fix getting latest version.

pipreqs/__init__.py, pipreqs/pipreqs.py, setup.py
Maintain the version info only in `pipreqs/__init__.py`.
=> Fix the wrong version info, close #19

.gitignore, pipreqs/pipreqs.py
Added .svn & .hg to directory ignores.
Also added *.bak to git ignores.
Addresses #25
=> Added .svn & .hg to directory ignores.

README.rst, pipreqs/pipreqs.py, tests/test_pipreqs.py
fix for windows, update readme and  fix lint warnning
=> fix for windows, update readme and  fix lint warnning

pipreqs/pipreqs.py
i'm sorry, i made a mistake on args.get()
=> fix(pipreqs/pipreqs.py): fix a mistake on args.get

pipreqs/pipreqs.py
Added an option to pass directories to ignore. 
The tests are unwritten but shouldn't be difficult to write - it seems there are already some issues with failing tests elsewhere so I didn't include them.
=> added ignore option

pipreqs/pipreqs.py, tests/test_pipreqs.py
=> Implement --print to output list of requirements to stdout

README.rst
=> Add --print to README

pipreqs/pipreqs.py
This should solve issue #65, but i have only made local tests.
=> BUG: remove package/version duplicates

pipreqs/pipreqs.py, tests/test_pipreqs.py
=> Implement '--clean' and '--diff'

pipreqs/pipreqs.py
This makes pipreqs dive into directories that are symlinks as Python
recognises these.  If symlinks are not followed, then the requirements
will be incorrect.
We also add a command line option to disable following of symlinks if
need be.
=> Follow symbolic linked directories

pipreqs/pipreqs.py
- Move logic that doesn't need to be inside of file context managers
outside
- Remove redundant `set` and `list` function calls
=> Clean up set and file usage in get_all_imports

HISTORY.rst
Via https://pypi.python.org/pypi/pipreqs/json
=> Add dates to recent changelog entries

pipreqs/mapping
added a mapping for django-prefetch extension
=> Add prefetch:django-prefetch

README.rst, pipreqs/pipreqs.py, tests/test_pipreqs.py
implemented feature of issue [#94](https://github.com/bndr/pipreqs/issues/94)
=> support omit package output version

pipreqs/mapping
Added MySQL-python and krbV module mappings
=> added MySQL-python and krbV mappings

pipreqs/mapping
https://github.com/aws-cloudformation/cfn-python-lint/
=> mapping cfn-lint

pipreqs/mapping
=> Add discord mapping/ Sort mapping file

pipreqs/mapping
For this package: https://pypi.org/project/pyAFQ/
Closes https://github.com/yeatmanlab/pyAFQ/issues/532
=> Add pyAFQ Mapping

pipreqs/mapping
https://pypi.org/project/aws-sam-translator/
https://github.com/awslabs/serverless-application-model
=> mapping aws-sam-translator

pipreqs/stdlib
This library is new in Python 3.6+
=> Added secrets to standard libraries file

pipreqs/mapping
closes https://github.com/bndr/pipreqs/issues/179
=> enh: include airflow mapping

tests/test_pipreqs.py, tox.ini
Apply pep8 rules
ignoring test files
extending max line to 120
=> applying pep8 rules

README.rst
Add authorship from the original PRs.
- Based on PR #369 and #396.
- Authors Muhammad-Aadil and mateuslatrova.
> OBS: Alternative way of editing the PRs.
=> add "copy to clipboard icon" in installation section

README.rst
update tests badge in readme [stale]
=> update tests badge in readme

pipreqs/mapping
=> Add OpenCV mapping

pipreqs/mapping
=> add pywintypes to mapping

pipreqs/pipreqs.py
=> Add .venv to ignored files
